### ISSUE TITLE
Upgrade plugin version

### ISSUE THREAD

**Issue by varenich** [elo7/cohort#12]
Hi,

Could you please upgrade and test your plagin to been able to use with last version of Kibana?

Thanks in advance

**Comment by cristyansv** [comment]
Is there a way to generate local distribution?

**Comment by varenich** [comment]
Do you mean local distribution of Kibana? Yes I can

17 окт. 2017 г. 9:29 PM пользователь "Cristyan Sepúlveda V" <
notifications@github.com> написал:

**Comment by mikedias** [comment]
Bumped to 5.6.3
