### ISSUE TITLE
Cannot install 5.3.0

### ISSUE THREAD

**Issue by RedCloudDC** [elo7/cohort#3]
@elo7

I modified package.json for my current version 5.3.0 however I get an error on install..

Retrieving metadata from plugin archive
Error: Could not find the End of Central Directory Record
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"

Is there a way to resolve this and install the plugin?

**Comment by MaloRchrd** [comment]
Hello @elo7, I was about to install your plugin on Es/Kibana 5.3.0, and just saw this issue. 

Is you plugin compatible with the lastest release (5.3.0) ? 
Thanks for your answer. 
Malo

**Comment by mikedias** [comment]
HI @RedCloudDC @MaloRchrd, we just released a version that is compatible with 5.3.0. You guys can try using the command below:
```
bin/kibana-plugin install https://github.com/elo7/cohort/releases/download/5.3.0/cohort-5.3.0.zip
```

**Comment by MaloRchrd** [comment]
Thank's a lot i'll try it very soon

**Comment by RedCloudDC** [comment]
works great! now if I only know how to use this chart with my data, I will email you thanks @mikedias

**Comment by noiala** [comment]
Hi guys,
I'm having the same issues but I'm running on version 5.3.1. With some other plugins I could resolve the version issues by editing my kibana package.json. If I change to 5.3.0 they break :(
Would it work if I just follow the "manual distribution" to create a 5.3.1 ?
