### ISSUE TITLE
Plugin is not compliant with kibana 5.5

### ISSUE THREAD

**Issue by tatdatpham** [elo7/cohort#6]
I installed ur plugin in kibana 5.5 and kibana doesn't working. I found some update for custome plugin in here
[https://github.com/elastic/kibana/issues/12707#issuecomment-314216338](https://github.com/elastic/kibana/issues/12707#issuecomment-314216338)

**Comment by mikedias** [comment]
Hi @tatdatpham thanks for pointing the issue. We fix it at PR #9
