### ISSUE TITLE
Install for Kibana 5.4.2 fails

### ISSUE THREAD

**Issue by spectroman** [elo7/cohort#8]
Changing the version on package.json and trying to install, I get:

    ERROR in ./area3d_vis/public/area3d_vis_controller.js
    Module not found: Error: Cannot resolve module 'vis' in /data/kibana/plugins/area3d_vis/public
     @ ./area3d_vis/public/area3d_vis_controller.js 17:11-25

**Comment by mikedias** [comment]
Hi @spectroman, the error that you pointed is about the `area3d_vis` plugin. Not sure how I can help you in this case.
